#!/usr/bin/env python3
"""
Placeholder for Western PDF skill discovery.

The actual PDF is generated by the hans-ai-whatsapp backend when the
agent outputs:
  WESTERN_PDF_REQUEST: dob=YYYY-MM-DD, tob=HH:MM, place=CITY, name=NAME
"""

print("WESTERN_PDF_REQUEST: dob=YYYY-MM-DD, tob=HH:MM, place=CITY, name=NAME")
